version: '3.6'

volumes:
  share: {}
  transmission: {}
  config: {}

services:
  base:
    build:
      context: .
      args:
        arch: ${arch}
    image: base_media

  samba:
    build:
      context: .
      dockerfile: SambaDockerfile
    restart: always
    ports:
      - 445:445
    volumes:
      - share:/share
    depends_on:
      - base

  transmission:
    build:
      context: .
      dockerfile: TransmissionDockerfile
    restart: always
    ports:
      - 9091:9091
    volumes:
      - share:/share
      - transmission:/var/lib/transmission-daemon
    depends_on:
      - base
    environment:
      - TRANSMISSION_WEB_HOME=/combustion/combustion-release

  jellyfin:
    network_mode: host # Enable DLNA
    image: "linuxserver/jellyfin:${tag}"
    environment:
      - PUID=1000
      - PGID=200
    volumes:
      - config:/config
      - share:/mnt/share:ro
      - /opt/vc/lib:/opt/vc/lib
#    ports:    # not active if host mode is activated
#      - 8096:8096
#      - 8920:8920 #optional
#      - 7359:7359/udp #optional
#      - 1900:1900/udp #optional
    devices:
      - /dev/dri:/dev/dri
    restart: always
    depends_on:
      - base
