volumes:
  share: {}
  transmission: {}
  minidlna_logs: {}
  minidlna_cache: {}
  metube_downloads: {}

services:
  base:
    build:
      context: .
    image: base_media

  samba:
    build:
      context: .
      dockerfile: SambaDockerfile
    restart: always
    ports:
      - 445:445
    volumes:
      - share:/share
    depends_on:
      - base
    environment:
      - USER=${USER}
      - PASS=${PASSWORD}

  transmission:
    build:
      context: .
      dockerfile: TransmissionDockerfile
    restart: always
    ports:
      - 9091:9091
    volumes:
      - share:/share
      - transmission:/var/lib/transmission-daemon
    depends_on:
      - base

  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: always
    ports:
      - 8081:8081
    volumes:
      - share:/share
      - metube_downloads:/downloads
    depends_on:
      - base
    environment:
      - UID=1000
      - GID=200
      - DEFAULT_THEME=dark
      - DOWNLOAD_DIR=/share/youtube
      - "YTDL_OPTIONS={\"writesubtitles\": true, \"writeautomaticsub\": true}"

  dlna:
    build:
      context: .
      dockerfile: DlnaDockerfile
    restart: always
    network_mode: "host"
    volumes:
      - share:/share:ro
      - minidlna_logs:/var/log/minidlna
      - minidlna_cache:/var/cache/minidlna
    depends_on:
      - base
    ulimits:
      nofile:
        soft: 65536
        hard: 1048576
    environment:
      - MINIDLNA_CACHE_DIR=/var/cache/minidlna
      - MINIDLNA_LOG_DIR=/var/log/minidlna
    security_opt:
      - no-new-privileges:true
    sysctls:
      - fs.file-max=2097152
      - net.core.rmem_max=268435456
      - net.core.wmem_max=268435456
      - net.ipv4.tcp_rmem=4096 131072 268435456
      - net.ipv4.tcp_wmem=4096 65536 268435456
      - net.ipv4.tcp_congestion_control=bbr
