version: '3'

volumes:
  share: {}
  transmission: {}
  conf: {}

services:
  base:
    build:
      context: .
    image: base_media

  samba:
    build:
      context: .
      dockerfile: SambaDockerfile
    restart: always
    ports:
      - 445:445
    volumes:
      - share:/share
    depends_on:
      - base
    env_file:
      - user.env

  transmission:
    build:
      context: .
      dockerfile: TransmissionDockerfile
    restart: always
    ports:
      - 9091:9091
    volumes:
      - share:/share
      - transmission:/var/lib/transmission-daemon
    depends_on:
      - base
    environment:
      - TRANSMISSION_WEB_HOME=/combustion/combustion-release

  emby:
    image: emby/embyserver_arm32v7
    network_mode: host # Enable DLNA and Wake-on-Lan
    environment:
      - UID=1000
      - GID=200
      - GIDLIST=100 # A comma-separated list of additional GIDs to run emby as (default: 2)
    volumes:
      - conf:/config
      - share:/mnt/share
#    ports:
#      - 8096:8096 # HTTP port
#      - 8920:8920 # HTTPS port
    devices:
      - /dev/vchiq:/dev/vchiq # MMAL/OMX on Raspberry Pi
    restart: always
    depends_on:
      - base
