media_dir=/share
friendly_name=DlnaSrv
inotify=yes
root_container=B
notify_interval=120
user=minidlna
network_interface=
max_connections=200
db_dir=/var/cache/minidlna
log_dir=/var/log/minidlna
strict_dlna=no
enable_tivo=no
root_container=B
log_level=error
serial=87654321
model_number=1
album_art_names=
force_sort_criteria=
